import Head from "next/head";
import { BsTwitter } from "react-icons/bs";
import { useState } from "react";
import Post from "@/components/UI/MainFeed/post";
import Sidebar from "@/components/UI/SideBar/sidebar";
import Sidefeed from "@/components/UI/SideFeed/Sidefeed";
import { GiHamburgerMenu } from "react-icons/gi";
import Overlay from "@/components/UI/SideBar/Overlay";
import PhoneSidebar from "@/components/UI/SideBar/PhoneSidebar";
import { useEffect } from "react";
import axios from "axios";
import { useSession } from "next-auth/react";
import Router from "next/router";

export default function Bookmark() {
  const { data: session } = useSession();

  const [content, setContent] = useState([]);

  useEffect(() => {
    if (!session) {
      Router.push("/auth/signin");
    }
    let temp = [];
    const getAllbookmarks = async () => {
      const allbookmarks = await axios.post(
        `${process.env.NEXTAUTH_URL}/api/getbookmarks`,
        {
          email: session.user.email,
        }
      );

      for (let i = allbookmarks.data.length - 1; i >= 0; i--) {
        temp.push(
          <Post
            _id={allbookmarks.data[i]._id}
            name={allbookmarks.data[i].name}
            likes={allbookmarks.data[i].likes}
            comments={allbookmarks.data[i].comments.length}
            content={allbookmarks.data[i].tweet}
            username={allbookmarks.data[i].email.split("@")[0]}
            time={allbookmarks.data[i].createdAt}
            isComment={false}
          />
        );
      }
      setContent([...temp]);
    };
    getAllbookmarks();
  }, [session]);

  const [Hamishidden, setHamIsHidden] = useState(false);
  let HamClass = `min-[500px]:hidden z-20 ease-in-out transition duration-200 bg-neutral-900 flex space-y-2 flex-col h-screen w-20 w-72 fixed left-0 top-0 border-r-2 border-neutral-900 items-center items-start py-4 ${
    Hamishidden ? "translate-x-0" : "-translate-x-72"
  }`;
  const HamClickHandler = () => {
    setHamIsHidden(!Hamishidden);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex mx-auto">
        <Sidebar />
        <PhoneSidebar classes={HamClass} />
        {Hamishidden && <Overlay onClickHandler={HamClickHandler} />}
        <div className="grow lg:min-w-[625px] max-w-[625px] flex flex-col min-[500px]:ml-20 xl:ml-80 border-r-2 border-neutral-900 ">
          <div className="min-[500px]:block hidden px-4 py-12 border-b-2 border-neutral-900 font-bold">
            Bookmarks
          </div>
          <div
            onClick={HamClickHandler}
            className=" min-[500px]:hidden block w-fit h-max p-2 fixed top-4 left-2 z-10"
          >
            {/* <div className="w-10 h-10 rounded-full bg-neutral-700"></div> */}
            <GiHamburgerMenu size={24} />
          </div>
          <div
            className="flex min-[500px]:hidden justify-center
         w-full py-6 text-sky-500 fixed top-0 backdrop-blur-md bg-black/30"
          >
            <BsTwitter size={24} />
          </div>
          {content}
        </div>
        <Sidefeed />
      </main>
    </>
  );
}
